<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class BancosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $bancos = [
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Outros',
                'nome_normalizado' => 'Outros',
                'numero_banco' => '0',
                'imagem' => '',
                'url' => '',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco Bradesco S.A.',
                'nome_normalizado' => 'Bradesco',
                'numero_banco' => '237',
                'imagem' => 'bradesco.png',
                'url' => 'http://www.bradesco.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco do Brasil S.A.',
                'nome_normalizado' => 'Banco do Brasil',
                'numero_banco' => '001',
                'imagem' => 'bb.png',
                'url' => 'http://www.bb.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco Santander (Brasil) S.A.',
                'nome_normalizado' => 'Santander',
                'numero_banco' => '033',
                'imagem' => 'santander.png',
                'url' => 'http://www.santander.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Caixa Econômica Federal',
                'nome_normalizado' => 'Caixa Econômica Federal',
                'numero_banco' => '104',
                'imagem' => 'caixa.png',
                'url' => 'http://www.caixa.gov.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Itaú Unibanco S.A.',
                'nome_normalizado' => 'Itaú Unibanco',
                'numero_banco' => '341',
                'imagem' => 'itau.png',
                'url' => 'http://www.itau.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco Inter S.A.',
                'nome_normalizado' => 'Banco Inter',
                'numero_banco' => '077',
                'imagem' => 'inter.png',
                'url' => 'https://bancointer.com.br/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Nu Pagamentos S.A.',
                'nome_normalizado' => 'Nubank',
                'numero_banco' => '260',
                'imagem' => 'nubank.png',
                'url' => 'https://nubank.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco C6 S.A.',
                'nome_normalizado' => 'C6 Bank',
                'numero_banco' => '336',
                'imagem' => 'c6bank.png',
                'url' => 'https://www.c6bank.com.br/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco BTG Pactual S.A.',
                'nome_normalizado' => 'BTG Pactual',
                'numero_banco' => '208',
                'imagem' => 'btg.png',
                'url' => 'https://www.btgpactual.com/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco Safra S.A.',
                'nome_normalizado' => 'Banco Safra',
                'numero_banco' => '422',
                'imagem' => 'safra.png',
                'url' => 'http://www.safra.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco Cooperativo Sicredi S.A.',
                'nome_normalizado' => 'Sicredi',
                'numero_banco' => '748',
                'imagem' => 'sicredi.png',
                'url' => 'http://www.sicredi.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco Cooperativo do Brasil S.A. - BANCOOB',
                'nome_normalizado' => 'Banco Cooperativo do Brasil - BANCOOB',
                'numero_banco' => '756',
                'imagem' => 'bancoob.png',
                'url' => 'http://www.bancoob.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco do Estado do Rio Grande do Sul S.A.',
                'nome_normalizado' => 'Banrisul',
                'numero_banco' => '041',
                'imagem' => 'banrisul.png',
                'url' => 'http://www.banrisul.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco do Estado do Espírito Santo S.A.',
                'nome_normalizado' => 'Banestes',
                'numero_banco' => '021',
                'imagem' => 'banestes.png',
                'url' => 'http://www.banestes.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco do Estado do Pará S.A.',
                'nome_normalizado' => 'Banpará',
                'numero_banco' => '037',
                'imagem' => 'banpara.png',
                'url' => 'https://www.banpara.b.br/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco do Estado de Sergipe S.A.',
                'nome_normalizado' => 'Banese',
                'numero_banco' => '047',
                'imagem' => 'banese.png',
                'url' => 'http://www.banese.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco de Brasília S.A.',
                'nome_normalizado' => 'Banco BRB',
                'numero_banco' => '070',
                'imagem' => 'brb.png',
                'url' => 'https://novo.brb.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco Votorantim S.A.',
                'nome_normalizado' => 'Banco Votorantim',
                'numero_banco' => '655',
                'imagem' => 'votorantim.png',
                'url' => 'http://www.bancovotorantim.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco Pan S.A.',
                'nome_normalizado' => 'Banco Pan',
                'numero_banco' => '623',
                'imagem' => 'pan.png',
                'url' => 'https://www.bancopan.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco Original S.A.',
                'nome_normalizado' => 'Original',
                'numero_banco' => '212',
                'imagem' => 'original.png',
                'url' => 'https://www.original.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco BMG S.A.',
                'nome_normalizado' => 'Banco BMG',
                'numero_banco' => '318',
                'imagem' => 'bmg.png',
                'url' => 'http://www.bancobmg.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco Daycoval S.A.',
                'nome_normalizado' => 'Banco Daycoval',
                'numero_banco' => '707',
                'imagem' => 'daycoval.png',
                'url' => 'http://www.daycoval.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco Citibank S.A.',
                'nome_normalizado' => 'Citibank',
                'numero_banco' => '745',
                'imagem' => 'citibank.png',
                'url' => 'https://corporateportal.brazil.citibank.com/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco Modal S.A.',
                'nome_normalizado' => 'Banco Modal',
                'numero_banco' => '746',
                'imagem' => 'modal.png',
                'url' => 'http://www.bancomodal.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco Fibra S.A.',
                'nome_normalizado' => 'Banco Fibra',
                'numero_banco' => '224',
                'imagem' => 'fibra.png',
                'url' => 'https://bancofibra.com.br/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco Pine S.A.',
                'nome_normalizado' => 'Banco Pine',
                'numero_banco' => '643',
                'imagem' => 'pine.png',
                'url' => 'https://www.pine.com/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco Mercantil do Brasil S.A.',
                'nome_normalizado' => 'Banco Mercantil do Brasil',
                'numero_banco' => '389',
                'imagem' => 'mercantil.png',
                'url' => 'https://bancomercantil.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco Sofisa S.A.',
                'nome_normalizado' => 'Banco Sofisa',
                'numero_banco' => '637',
                'imagem' => 'sofisa.png',
                'url' => 'http://www.sofisa.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco Topázio S.A.',
                'nome_normalizado' => 'Banco Topázio',
                'numero_banco' => '082',
                'imagem' => 'topazio.png',
                'url' => 'http://www.bancotopazio.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco Tricury S.A.',
                'nome_normalizado' => 'Banco Tricury',
                'numero_banco' => '018',
                'imagem' => 'tricury.png',
                'url' => 'http://www.tricury.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco VR S.A.',
                'nome_normalizado' => 'Banco VR',
                'numero_banco' => '610',
                'imagem' => 'vr.png',
                'url' => 'https://bancovr.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco Genial S.A.',
                'nome_normalizado' => 'Banco Genial',
                'numero_banco' => '278',
                'imagem' => 'genial.png',
                'url' => 'https://www.bancogenial.com',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco Rendimento S.A.',
                'nome_normalizado' => 'Banco Rendimento',
                'numero_banco' => '633',
                'imagem' => 'rendimento.png',
                'url' => 'http://www.rendimento.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco Semear S.A.',
                'nome_normalizado' => 'Banco Semear',
                'numero_banco' => '743',
                'imagem' => 'semear.png',
                'url' => 'https://www.bancosemear.com.br/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco Ribeirão Preto S.A.',
                'nome_normalizado' => 'Banco Ribeirão Preto',
                'numero_banco' => '741',
                'imagem' => 'ribeirao.png',
                'url' => 'https://www.brp.com.br/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco Triângulo S.A.',
                'nome_normalizado' => 'Tribanco',
                'numero_banco' => '634',
                'imagem' => 'tribanco.png',
                'url' => 'http://www.tribanco.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco Voiter S.A.',
                'nome_normalizado' => 'Voiter',
                'numero_banco' => '653',
                'imagem' => 'voiter.png',
                'url' => 'https://www.voiter.com/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco Omni S.A.',
                'nome_normalizado' => 'Omni',
                'numero_banco' => '613',
                'imagem' => 'omni.png',
                'url' => 'https://www.omni.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco Paulista S.A.',
                'nome_normalizado' => 'Banco Paulista',
                'numero_banco' => '611',
                'imagem' => 'paulista.png',
                'url' => 'http://www.bancopaulista.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco Guanabara S.A.',
                'nome_normalizado' => 'Banco Guanabara',
                'numero_banco' => '612',
                'imagem' => 'guanabara.png',
                'url' => 'https://www.bancoguanabara.com.br/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco Master S.A.',
                'nome_normalizado' => 'Banco Master',
                'numero_banco' => '243',
                'imagem' => 'master.png',
                'url' => 'https://www.bancomaster.com.br/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco Porto Seguro S.A.',
                'nome_normalizado' => 'Banco Porto Seguro',
                'numero_banco' => '724',
                'imagem' => 'portoseguro.png',
                'url' => 'https://www.portoseguro.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco Randon S.A.',
                'nome_normalizado' => 'Banco Randon',
                'numero_banco' => '088',
                'imagem' => 'randon.png',
                'url' => 'https://bancorandon.com/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco Rodobens S.A.',
                'nome_normalizado' => 'Banco Rodobens',
                'numero_banco' => '120',
                'imagem' => 'rodobens.png',
                'url' => 'http://www.rodobens.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco Simples S.A.',
                'nome_normalizado' => 'Banco Simples',
                'numero_banco' => '749',
                'imagem' => 'simples.png',
                'url' => 'http://www.bancosimples.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco Société Générale Brasil S.A.',
                'nome_normalizado' => 'Banco Société Générale Brasil',
                'numero_banco' => '366',
                'imagem' => 'societe.png',
                'url' => 'https://societegeneralebrasil.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco Sumitomo Mitsui Brasileiro S.A.',
                'nome_normalizado' => 'Banco Sumitomo Mitsui Brasileiro',
                'numero_banco' => '464',
                'imagem' => 'sumitomo.png',
                'url' => 'https://www.smbcgroup.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco Toyota do Brasil S.A',
                'nome_normalizado' => 'Banco Toyota do Brasil',
                'numero_banco' => '387',
                'imagem' => 'toyota.png',
                'url' => 'http://www.bancotoyota.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco Volkswagen S.A.',
                'nome_normalizado' => 'Banco Volkswagen',
                'numero_banco' => '393',
                'imagem' => 'volkswagen.png',
                'url' => 'https://www.vwfs.com.br/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco Volvo (Brasil) S.A.',
                'nome_normalizado' => 'Banco Volvo (Brasil)',
                'numero_banco' => 'M23',
                'imagem' => 'volvo.png',
                'url' => 'https://www.volvofinancialservices.com/br/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco WestLB do Brasil S.A.',
                'nome_normalizado' => 'Banco WestLB do Brasil',
                'numero_banco' => '370',
                'imagem' => 'westlb.png',
                'url' => 'http://www.westlb.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco Woori Bank do Brasil S.A.',
                'nome_normalizado' => 'Woori Bank do Brasil',
                'numero_banco' => '124',
                'imagem' => 'woori.png',
                'url' => 'https://wooribank.com.br/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Banco Yamaha Motor do Brasil S.A.',
                'nome_normalizado' => 'Banco Yamaha Motor',
                'numero_banco' => '475',
                'imagem' => 'yamaha.png',
                'url' => 'https://www.yamahaservicosfinanceiros.com.br/banco',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Bank of America Merrill Lynch Banco Múltiplo S.A.',
                'nome_normalizado' => 'Merril | Bank of America',
                'numero_banco' => '755',
                'imagem' => 'merril.png',
                'url' => 'http://www.ml.com',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'BMP Money Plus',
                'nome_normalizado' => 'BMP Money Plus',
                'numero_banco' => '274',
                'imagem' => 'moneyp.png',
                'url' => 'https://www.moneyp.com.br/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Carteira',
                'nome_normalizado' => 'Carteira',
                'numero_banco' => '',
                'imagem' => 'carteira.png',
                'url' => '',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Celcoin IP S.A.',
                'nome_normalizado' => 'Celcoin Pagamentos',
                'numero_banco' => '509',
                'imagem' => 'celcoin.png',
                'url' => 'https://celcoin.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Central Cooperativa de Crédito no Estado do Espírito Santo - CECOOP',
                'nome_normalizado' => 'CECOOP',
                'numero_banco' => '114',
                'imagem' => 'cecoop.png',
                'url' => 'https://cecoop.com.br/central/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Chase Credit Cards',
                'nome_normalizado' => 'Chase',
                'numero_banco' => '',
                'imagem' => 'chase.png',
                'url' => 'https://creditcards.chase.com/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Cielo S.A.',
                'nome_normalizado' => 'Cielo',
                'numero_banco' => '362',
                'imagem' => 'cielo.png',
                'url' => 'https://www.cielo.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Clear CTVM S.A.',
                'nome_normalizado' => 'Clear Corretora',
                'numero_banco' => '',
                'imagem' => 'clear.png',
                'url' => 'https://corretora.clear.com.br/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Conta Simples',
                'nome_normalizado' => 'ContaSimples',
                'numero_banco' => '',
                'imagem' => 'contasimples.png',
                'url' => 'https://contasimples.com',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Cora SCD S.A.',
                'nome_normalizado' => 'Cora',
                'numero_banco' => '403',
                'imagem' => 'cora.png',
                'url' => 'https://www.cora.com.br/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Credialiança Cooperativa de Crédito Rural',
                'nome_normalizado' => 'CrediAliança',
                'numero_banco' => '098',
                'imagem' => 'credialianca.png',
                'url' => 'https://www.credialianca.com.br/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Credisan Cooperativa de Crédito',
                'nome_normalizado' => 'Credisan',
                'numero_banco' => '089',
                'imagem' => 'credisan.png',
                'url' => 'https://portal.credisan.com.br/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'CrediSIS - Central de Cooperativas de Crédito Ltda',
                'nome_normalizado' => 'CrediSIS',
                'numero_banco' => '097',
                'imagem' => 'credisis.png',
                'url' => 'https://credisis.com.br/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Cresol Confederação',
                'nome_normalizado' => 'Cresol',
                'numero_banco' => '133',
                'imagem' => 'cresol.png',
                'url' => 'https://cresol.com.br/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Deutsche Bank S.A. - Banco Alemão',
                'nome_normalizado' => 'Deutsche Bank Brasil',
                'numero_banco' => '487',
                'imagem' => 'deutsche.png',
                'url' => 'https://country.db.com/brazil',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Dock IP S.A.',
                'nome_normalizado' => 'Dock',
                'numero_banco' => '301',
                'imagem' => 'dock.png',
                'url' => 'https://dock.tech/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Efí S.A. - IP',
                'nome_normalizado' => 'Efí Bank',
                'numero_banco' => '364',
                'imagem' => 'efi.png',
                'url' => 'https://sejaefi.com.br/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Galax pay',
                'nome_normalizado' => 'Galaxpay',
                'numero_banco' => '',
                'imagem' => 'galaxpay.png',
                'url' => '',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Goldman Sachs do Brasil Banco Múltiplo S.A.',
                'nome_normalizado' => 'Goldman Sachs do Brasil',
                'numero_banco' => '064',
                'imagem' => 'goldman.png',
                'url' => 'https://www.goldmansachs.com/worldwide/brazil/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Haitong Banco de Investimento do Brasil S.A.',
                'nome_normalizado' => 'Haitong BI do Brasil',
                'numero_banco' => '078',
                'imagem' => 'haitong.png',
                'url' => 'https://www.haitongib.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Hipercard Banco Múltiplo S.A.',
                'nome_normalizado' => 'Hipercard',
                'numero_banco' => '062',
                'imagem' => 'hipercard.png',
                'url' => 'http://www.hipercard.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'HSBC Bank Brasil S.A. - Banco Múltiplo',
                'nome_normalizado' => 'HSBC',
                'numero_banco' => '399',
                'imagem' => 'hsbc.png',
                'url' => 'http://www.hsbc.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'InfinitePay',
                'nome_normalizado' => 'InfinitePay',
                'numero_banco' => '999',
                'imagem' => 'infinitepay.png',
                'url' => 'https://www.infinitepay.io/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'ING Bank N.V.',
                'nome_normalizado' => 'ING Bank N.V.',
                'numero_banco' => '492',
                'imagem' => 'ing.png',
                'url' => 'http://www.ing.com',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'JPMorgan Chase Bank',
                'nome_normalizado' => 'JPMorgan Chase Bank',
                'numero_banco' => '488',
                'imagem' => 'jpmorgan.png',
                'url' => 'http://www.jpmorganchase.com',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Lecca Crédito, Financiamento e Investimento S.A.',
                'nome_normalizado' => 'Lecca CFI',
                'numero_banco' => '105',
                'imagem' => 'lecca.png',
                'url' => 'https://www.lecca.com.br/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Mercado Pago',
                'nome_normalizado' => 'Mercado Pago',
                'numero_banco' => '323',
                'imagem' => 'mercadopago.png',
                'url' => 'https://www.mercadopago.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Modo Bank S.A.',
                'nome_normalizado' => 'ModoBank',
                'numero_banco' => '',
                'imagem' => 'modobank.png',
                'url' => 'https://modobank.com/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Natixis Brasil S.A. Banco Múltiplo',
                'nome_normalizado' => 'Natixis BrasilBanco Múltiplo',
                'numero_banco' => '014',
                'imagem' => 'natixis.png',
                'url' => 'https://americas.cib.natixis.com/brazil',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'NBC Bank Brasil S.A. - Banco Múltiplo',
                'nome_normalizado' => 'NBC Bank Brasil- Banco Múltiplo',
                'numero_banco' => '753',
                'imagem' => 'nbc.png',
                'url' => 'http://www.nbcbank.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Neon Pagamentos S.A. IP',
                'nome_normalizado' => 'Neon',
                'numero_banco' => '536',
                'imagem' => 'neon.png',
                'url' => 'https://neon.com.br/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Next Tecnologia e Serviços Digitais S.A.',
                'nome_normalizado' => 'Next',
                'numero_banco' => '',
                'imagem' => 'next.png',
                'url' => 'https://next.me',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Nomad Fintech Inc.',
                'nome_normalizado' => 'Nomad',
                'numero_banco' => '',
                'imagem' => 'nomad.png',
                'url' => 'https://www.nomadglobal.com/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Nu Invest CV S.A',
                'nome_normalizado' => 'NuInvest',
                'numero_banco' => '',
                'imagem' => 'nuinvest.png',
                'url' => 'https://www.nuinvest.com.br/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Oliveira Trust DTVM S.A.',
                'nome_normalizado' => 'Oliveira Trust',
                'numero_banco' => '111',
                'imagem' => 'oliveira.png',
                'url' => 'https://www.oliveiratrust.com.br/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Outros',
                'nome_normalizado' => 'Outros',
                'numero_banco' => '',
                'imagem' => 'outros.png',
                'url' => '',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Pagbank',
                'nome_normalizado' => 'Pagbank',
                'numero_banco' => '290',
                'imagem' => 'pagbank.png',
                'url' => '',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Paraná Banco S.A.',
                'nome_normalizado' => 'Paraná Banco',
                'numero_banco' => '254',
                'imagem' => 'parana.png',
                'url' => 'https://site.paranabanco.com.br/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Paypal',
                'nome_normalizado' => 'Paypal',
                'numero_banco' => '',
                'imagem' => 'paypal.png',
                'url' => 'https://paypal.com',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'PayU',
                'nome_normalizado' => 'PayU',
                'numero_banco' => '',
                'imagem' => 'payu.png',
                'url' => 'https://brazil.payu.com',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Picpay Servicos S.A.',
                'nome_normalizado' => 'PicPay',
                'numero_banco' => '380',
                'imagem' => 'picpay.png',
                'url' => '',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Planner Corretora de Valores S.A.',
                'nome_normalizado' => 'Planner',
                'numero_banco' => '100',
                'imagem' => 'planner.png',
                'url' => 'https://www.planner.com.br/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'PÓLOCRED SOCIEDADE DE CRÉDITO AO MICROEMPREENDEDOR E À EMPRESA DE PEQUENO PORTE',
                'nome_normalizado' => 'PoloCred',
                'numero_banco' => '093',
                'imagem' => 'polocred.png',
                'url' => 'https://www.polocred.com.br/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'RecargaPay IP Ltda',
                'nome_normalizado' => 'RecargaPay',
                'numero_banco' => '',
                'imagem' => 'recargapay.png',
                'url' => 'https://recargapay.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Rico Corretora',
                'nome_normalizado' => 'Rico Corretora',
                'numero_banco' => '',
                'imagem' => 'rico.png',
                'url' => 'https://www.rico.com.vc/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Scotiabank Brasil S.A. Banco Múltiplo',
                'nome_normalizado' => 'Scotiabank Brasil',
                'numero_banco' => '751',
                'imagem' => 'scotiabank.png',
                'url' => 'http://www.br.scotiabank.com',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Sicoob',
                'nome_normalizado' => 'Sicoob',
                'numero_banco' => '756',
                'imagem' => 'sicoob.png',
                'url' => 'https://www.sicoob.com.br/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Stark Bank',
                'nome_normalizado' => 'Stark Bank',
                'numero_banco' => '462',
                'imagem' => 'stark.png',
                'url' => 'https://starkbank.com/br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Stone Pagamentos S.A',
                'nome_normalizado' => 'Stone Pagamentos',
                'numero_banco' => '197',
                'imagem' => 'stone.png',
                'url' => 'https://www.stone.com.br/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'SumUp SCD S.A.',
                'nome_normalizado' => 'SumUp',
                'numero_banco' => '404',
                'imagem' => 'sumup.png',
                'url' => 'https://www.sumup.com/pt-br/bank/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Superdigital IP S.A.',
                'nome_normalizado' => 'Superdigital',
                'numero_banco' => '340',
                'imagem' => 'superdigital.png',
                'url' => 'https://superdigital.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'TD Bank, N.A. ',
                'nome_normalizado' => 'TD Bank',
                'numero_banco' => '',
                'imagem' => 'tdbank.png',
                'url' => 'https://www.td.com',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Ticket',
                'nome_normalizado' => 'Ticket',
                'numero_banco' => '',
                'imagem' => 'ticket.png',
                'url' => 'https://www.ticket.com.br/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Transfeera IP S.A.',
                'nome_normalizado' => 'Transfeera',
                'numero_banco' => 'TRA',
                'imagem' => 'transfeera.png',
                'url' => 'https://transfeera.com',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Travelex Banco de Câmbio S.A.',
                'nome_normalizado' => 'Travelex',
                'numero_banco' => '095',
                'imagem' => 'travelex.png',
                'url' => 'https://www.travelexbank.com.br/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Trigg',
                'nome_normalizado' => 'Trigg',
                'numero_banco' => '',
                'imagem' => 'trigg.png',
                'url' => 'https://trigg.com.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Unicred',
                'nome_normalizado' => 'Unicred',
                'numero_banco' => '136',
                'imagem' => 'unicred.png',
                'url' => 'https://www.unicred.com.br/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'UNIPRIME Central – Central Interestadual de Cooperativas de Crédito Ltda.',
                'nome_normalizado' => 'Uniprime Central',
                'numero_banco' => '099',
                'imagem' => 'uniprime.png',
                'url' => 'https://www.uniprime.com.br/singular/central',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'UNIPRIME DO BRASIL - COOPERATIVA DE CRÉDITO',
                'nome_normalizado' => 'UNIPRIME DO BRASIL - COOP',
                'numero_banco' => '084',
                'imagem' => 'uniprimebrasil.png',
                'url' => 'https://www.uniprimedobrasil.com.br/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Urbe.Me',
                'nome_normalizado' => 'Urbe.Me',
                'numero_banco' => '',
                'imagem' => 'urbeme.png',
                'url' => 'http://urbe.me/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Viacredi',
                'nome_normalizado' => 'Viacredi',
                'numero_banco' => '085',
                'imagem' => 'viacredi.png',
                'url' => 'https://www.viacredi.coop.br',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Warren CTVMC Ltda',
                'nome_normalizado' => 'Warren',
                'numero_banco' => '371',
                'imagem' => 'warren.png',
                'url' => 'https://warren.com.br/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Wells Fargo',
                'nome_normalizado' => 'Wells Fargo',
                'numero_banco' => '',
                'imagem' => 'wellsfargo.png',
                'url' => 'https://www.wellsfargo.com/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Western Union do Brasil S.A.',
                'nome_normalizado' => 'Western Union',
                'numero_banco' => '119',
                'imagem' => 'westernunion.png',
                'url' => 'https://www.bancowesternunion.com.br/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Will S.A. IP',
                'nome_normalizado' => 'Will Bank',
                'numero_banco' => '280',
                'imagem' => 'will.png',
                'url' => 'https://www.willbank.com.br/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Wirecard',
                'nome_normalizado' => 'Wirecard',
                'numero_banco' => '000',
                'imagem' => 'wirecard.png',
                'url' => '',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'Woop Sicredi',
                'nome_normalizado' => 'Woop Sicredi',
                'numero_banco' => '',
                'imagem' => 'woopsicredi.png',
                'url' => 'https://woopsicredi.com',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nome_institucional' => 'XP Investimentos CCTVM S.A.',
                'nome_normalizado' => 'XP Investimentos',
                'numero_banco' => '102',
                'imagem' => 'xp.png',
                'url' => 'https://www.xpi.com.br/',
                'status' => 1,
                'criado_em' => now(),
                'atualizado_em' => now(),
            ],
        ];

        DB::table('bancos')->insert($bancos);
    }
}
