#!/bin/bash

# Script com comandos para executar no servidor após o deploy
# Execute este script no servidor após o deploy.sh

SERVER_USER="bxfcgip2"
REMOTE_PATH="/home/bxfcgip2/www"

echo "=========================================="
echo "  Comandos Pós-Deploy - Execute no Servidor"
echo "=========================================="
echo ""
echo "Conecte-se ao servidor:"
echo "  ssh ${SERVER_USER}@jamees.com"
echo ""
echo "Depois execute os seguintes comandos:"
echo ""
echo "cd $REMOTE_PATH"
echo ""
echo "# Instalar dependências (produção)"
echo "composer install --no-dev --optimize-autoloader"
echo ""
echo "# Limpar e recriar cache"
echo "php artisan config:clear"
echo "php artisan route:clear"
echo "php artisan view:clear"
echo "php artisan cache:clear"
echo ""
echo "# Criar cache de produção"
echo "php artisan config:cache"
echo "php artisan route:cache"
echo "php artisan view:cache"
echo ""
echo "# Executar migrações (se necessário)"
echo "php artisan migrate --force"
echo ""
echo "# Ajustar permissões"
echo "chmod -R 775 storage bootstrap/cache"
echo "chown -R ${SERVER_USER}:${SERVER_USER} storage bootstrap/cache"
echo ""
echo "# Verificar se .env existe"
echo "ls -la .env"
echo ""
echo "# Se não existir, criar a partir do .env.example"
echo "cp .env.example .env"
echo "php artisan key:generate"
echo ""
echo "=========================================="

